name: Build Windows EXE

on:
  workflow_dispatch:
  push:
    tags: ["v*"]   # opcional: al publicar un tag v1.0, etc.

jobs:
  win-build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if (Test-Path requirements.txt) { pip install -r requirements.txt }
          pip install pyinstaller

      - name: Build .exe
        run: |
          # Ajusta el comando a tus necesidades (icono, datos, hidden-imports, etc.)
          pyinstaller --onefile --name MiApp `
            --add-data "defaults\config.yaml;defaults" `
            app.py

      - name: Package artifact
        run: |
          New-Item -ItemType Directory -Force -Path dist_pkg | Out-Null
          Copy-Item dist\MiApp.exe dist_pkg\
          if (Test-Path .\config.yaml) { Copy-Item .\config.yaml dist_pkg\ }
          if (Test-Path .\data) { Copy-Item .\data dist_pkg\data -Recurse }
          Compress-Archive -Path dist_pkg\* -DestinationPath MiApp-windows-x64.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MiApp-windows-x64
          path: MiApp-windows-x64.zip